table Dim_EmpLength
	lineageTag: 457514c7-94ca-4948-a720-f376f305e7dd

	column emp_length
		dataType: string
		lineageTag: 791fff5d-ccb2-4abe-aedc-fc242a86fbba
		summarizeBy: none
		sourceColumn: emp_length

		annotation SummarizationSetBy = Automatic

	column EmpLengthBucket
		dataType: string
		lineageTag: 62988960-0c8a-4c2e-be27-fb2ee85ab1f9
		summarizeBy: none
		sourceColumn: EmpLengthBucket

		annotation SummarizationSetBy = Automatic

	column EmpLengthSortOrder
		dataType: string
		lineageTag: 551c7881-cd98-4825-9a6e-c2f5da7d4515
		summarizeBy: none
		sourceColumn: EmpLengthSortOrder

		annotation SummarizationSetBy = Automatic

	column EmpLengthKey
		dataType: int64
		formatString: 0
		lineageTag: 27d30286-6d11-418c-9449-ffb80566bba9
		summarizeBy: none
		sourceColumn: EmpLengthKey

		annotation SummarizationSetBy = Automatic

	partition Dim_EmpLength = m
		mode: import
		source = ```
				let
				    Source = Staging_Loans,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"emp_length"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Custom" = Table.AddColumn(#"Removed Duplicates", "EmpLengthBucket", each 
				    if [emp_length] = null or [emp_length] = "" then "Unknown"
				    else if [emp_length] = "< 1 year" then "<1"
				    else if [emp_length] = "10+ years" then "10+"
				    else
				        let yrs = Number.FromText(Text.BeforeDelimiter([emp_length], " "))
				        in if yrs <= 3 then "1-3" else if yrs <= 6 then "4-6" else "7-9"
				),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "EmpLengthSortOrder", each if [EmpLengthBucket] = "Unknown" then 0
				    else if [EmpLengthBucket] = "<1" then 1
				    else if [EmpLengthBucket] = "1-3" then 2
				    else if [EmpLengthBucket] = "4-6" then 3
				    else if [EmpLengthBucket] = "7-9" then 4    else 5),
				    #"Added Index" = Table.AddIndexColumn(#"Added Custom1", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "EmpLengthKey"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

